server:
  port: 12000

spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.149.101:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123

  application:
    name: spzx-authority-manage

  config:
    import:
      - optional:nacos:${spring.application.name}.yaml  # 导入共享配置（常用）

  cloud:
    nacos:
      config:
        server-addr: 192.168.149.101:8848 # 配置中心地址
      discovery:
        server-addr: 192.168.149.101:8848  # 服务发现地址

  data:
    redis:
      host: 192.168.149.101
      port: 6379

  session:
    store-type: redis
    timeout: 30m

  jackson:
    time-zone: Asia/Shanghai # 时区

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    groups-order: DESC
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'role-manage' # 这里配置默认分组
      paths-to-match: '/**'
      packages-to-scan: com.cell.spzx.role_manage.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 打印
  global-config:
    db-config:
      id-type: auto        # 主键策略
      logic-delete-value: 1
      logic-not-delete-value: 0

spzx:
  auth:
    noAuthUrls:
      - /doc.html            # Knife4j doc 页面
      - /swagger-ui.html     # SpringDoc UI 页面
      - /v3/api-docs/**      # JSON 文档接口
      - /swagger-ui/**       # SpringDoc 静态资源
      - /webjars/**          # webjars 静态资源
      - /favicon.ico         # 点击接口进入文档页面去加载接口信息，同时浏览器也自动请求 /favicon.ico
      - /error
      - /role-manage/**
      - /sys_user/**








